Dockerfile.apt.template
services/mariadb/Dockerfile
services/mysql/Dockerfile
services/php-apache/Dockerfile
services/php-fpm/Dockerfile

* Upgrade to git 1.9 on wheezy-based images
* Ensure a "tugboat" database is created on mariadb images
* Install mysql-client on php images

Image refinements

---

services/percona/Dockerfile
services/percona/README.md
services/percona/files/mysql/tugboat.cnf
services/percona/run

@bchavet did I do this correctly?

Add Percona images

---

services/php-apache/Dockerfile
services/php-fpm/Dockerfile

This PR adds some environment variables that will ensure that composer can run non-interactively without error.

Composer environment variables: discard changes, and allow root

---

services/php-apache/Dockerfile
services/php-fpm/Dockerfile

php-7.4RC1 doesn't like xdebug < 2.8

install xdebug-2.8-beta if other versions fail

---

services/rabbitmq/manifest
services/rabbitmq/run

Add a RabbitMQ image #62

---

services/varnish/Dockerfile
services/varnish/manifest

#76 upgrade varnish ubuntu to jammy and remove wheezy-backports

---

services/php-apache/Dockerfile
services/php-fpm/Dockerfile

Fixes https://github.com/TugboatQA/images/issues/82

Enable WebP support in GD

---

Makefile
services/mariadb/Dockerfile
services/mariadb/files/mysql/tugboat.cnf
services/mysql/Dockerfile
services/mysql/files/mysql/tugboat.cnf
services/percona-server/files/mysql/tugboat.cnf
services/percona/files/mysql/tugboat.cnf

#85 feat: disable binary log on mysql and friends

---

services/php-apache/Dockerfile
services/php-fpm/Dockerfile

#87 fix: standardize gd configure command for all PHP versions

---

services/cypress-included/manifest

feat: add a cypress/included image #90

---

.editorconfig
Makefile
build

feat: push and rm in build to save disk

---

services/mariadb/run

fix: call mariadbd instead of mysqld #109

---

services/dynamodb/Dockerfile
services/dynamodb/manifest
services/dynamodb/run

feat: add dynamodb image #107

---

Makefile
README.md
build
services/httpd/manifest

Resolves #117 
To test:
1. Create an `httpd` repository on Docker hub under your username
2. Create a docker hub API token and login in your terminal using `docker login`
3. Modify `services/httpd/manifest` and add `NAMESPACE=[your docker hub username]`
4. Run `push_and_rm=1 make httpd`
5. When complete, visit the **Tags** on docker hub and check to see if each tag has multiple platforms

feat: support multi-platform image generation #117

---

Makefile
build

fix: use buildx to build to support cross-platform images on platforms without QEMU

---

services/php-apache/Dockerfile
services/php-fpm/Dockerfile
services/php-nginx/Dockerfile

This installs the opcache extension on php-* services as per issue #21 
Resolves: #21

Add opcache to php-* services

---

scripts/bakefile.sh

#131 fix: only cache on main branch; use mode=min

---

templates/Dockerfile.apt.template

resolves #126 
See https://lullabot.slack.com/archives/C019JP1EN1Y/p1693850955726219

feat: improve performance of apt-get with eatmydata #126

---

services/postgis/Dockerfile
services/postgis/files/docker-entrypoint-initdb.d/init-tugboat-user.sh
services/postgis/manifest
services/postgis/run

feat: postgis image

---

templates/Dockerfile.apk.template
templates/Dockerfile.apt.template
templates/Dockerfile.yum.template

feat: install jq on all images #141
